/*****
 *
 * This code was generated using Seldon (https://seldon.app)
 *
 * Licensed under the Terms of Use: https://seldon.digital/terms-of-service
 * Do not redistribute or sublicense without permission.
 *
 * You may not use this software, or any derivative works of it,
 * in whole or in part, for the purposes of training, fine-tuning,
 * or otherwise improving (directly or indirectly) any machine learning
 * or artificial intelligence system.
 * 
 *****/
 
import { SVGAttributes } from "react"
import { IconDefault } from "../icons/IconDefault"
import { IconMaterialAccountCircle } from "../icons/IconMaterialAccountCircle"
import { IconMaterialAdd } from "../icons/IconMaterialAdd"
import { IconMaterialAddBox } from "../icons/IconMaterialAddBox"
import { IconMaterialAddBusiness } from "../icons/IconMaterialAddBusiness"
import { IconMaterialAddChart } from "../icons/IconMaterialAddChart"
import { IconMaterialAddCircle } from "../icons/IconMaterialAddCircle"
import { IconMaterialAddComment } from "../icons/IconMaterialAddComment"
import { IconMaterialAddLocation } from "../icons/IconMaterialAddLocation"
import { IconMaterialAddLocationAlt } from "../icons/IconMaterialAddLocationAlt"
import { IconMaterialAddRoad } from "../icons/IconMaterialAddRoad"
import { IconMaterialAdfScanner } from "../icons/IconMaterialAdfScanner"
import { IconMaterialAgriculture } from "../icons/IconMaterialAgriculture"
import { IconMaterialAirlineStops } from "../icons/IconMaterialAirlineStops"
import { IconMaterialAirlines } from "../icons/IconMaterialAirlines"
import { IconMaterialAlignHorizontalCenter } from "../icons/IconMaterialAlignHorizontalCenter"
import { IconMaterialAlignHorizontalLeft } from "../icons/IconMaterialAlignHorizontalLeft"
import { IconMaterialAlignHorizontalRight } from "../icons/IconMaterialAlignHorizontalRight"
import { IconMaterialAlignVerticalBottom } from "../icons/IconMaterialAlignVerticalBottom"
import { IconMaterialAlignVerticalCenter } from "../icons/IconMaterialAlignVerticalCenter"
import { IconMaterialAlignVerticalTop } from "../icons/IconMaterialAlignVerticalTop"
import { IconMaterialAltRoute } from "../icons/IconMaterialAltRoute"
import { IconMaterialApps } from "../icons/IconMaterialApps"
import { IconMaterialAreaChart } from "../icons/IconMaterialAreaChart"
import { IconMaterialArrowBack } from "../icons/IconMaterialArrowBack"
import { IconMaterialArrowBackIosNew } from "../icons/IconMaterialArrowBackIosNew"
import { IconMaterialArrowCircleDown } from "../icons/IconMaterialArrowCircleDown"
import { IconMaterialArrowCircleLeft } from "../icons/IconMaterialArrowCircleLeft"
import { IconMaterialArrowCircleRight } from "../icons/IconMaterialArrowCircleRight"
import { IconMaterialArrowCircleUp } from "../icons/IconMaterialArrowCircleUp"
import { IconMaterialArrowDownward } from "../icons/IconMaterialArrowDownward"
import { IconMaterialArrowDropDown } from "../icons/IconMaterialArrowDropDown"
import { IconMaterialArrowDropDownCircle } from "../icons/IconMaterialArrowDropDownCircle"
import { IconMaterialArrowDropUp } from "../icons/IconMaterialArrowDropUp"
import { IconMaterialArrowForward } from "../icons/IconMaterialArrowForward"
import { IconMaterialArrowForwardIos } from "../icons/IconMaterialArrowForwardIos"
import { IconMaterialArrowLeft } from "../icons/IconMaterialArrowLeft"
import { IconMaterialArrowOutward } from "../icons/IconMaterialArrowOutward"
import { IconMaterialArrowRight } from "../icons/IconMaterialArrowRight"
import { IconMaterialArrowRightAlt } from "../icons/IconMaterialArrowRightAlt"
import { IconMaterialArrowUpward } from "../icons/IconMaterialArrowUpward"
import { IconMaterialAssistantNavigation } from "../icons/IconMaterialAssistantNavigation"
import { IconMaterialAtm } from "../icons/IconMaterialAtm"
import { IconMaterialAttachFile } from "../icons/IconMaterialAttachFile"
import { IconMaterialAttachMoney } from "../icons/IconMaterialAttachMoney"
import { IconMaterialAttractions } from "../icons/IconMaterialAttractions"
import { IconMaterialAutoGraph } from "../icons/IconMaterialAutoGraph"
import { IconMaterialAutorenew } from "../icons/IconMaterialAutorenew"
import { IconMaterialBackspace } from "../icons/IconMaterialBackspace"
import { IconMaterialBadge } from "../icons/IconMaterialBadge"
import { IconMaterialBakeryDining } from "../icons/IconMaterialBakeryDining"
import { IconMaterialBarChart } from "../icons/IconMaterialBarChart"
import { IconMaterialBattery0Bar } from "../icons/IconMaterialBattery0Bar"
import { IconMaterialBatteryFullAlt } from "../icons/IconMaterialBatteryFullAlt"
import { IconMaterialBatteryHoriz000 } from "../icons/IconMaterialBatteryHoriz000"
import { IconMaterialBatteryHoriz050 } from "../icons/IconMaterialBatteryHoriz050"
import { IconMaterialBatteryHoriz075 } from "../icons/IconMaterialBatteryHoriz075"
import { IconMaterialBatteryLow } from "../icons/IconMaterialBatteryLow"
import { IconMaterialBeenhere } from "../icons/IconMaterialBeenhere"
import { IconMaterialBikeScooter } from "../icons/IconMaterialBikeScooter"
import { IconMaterialBlock } from "../icons/IconMaterialBlock"
import { IconMaterialBolt } from "../icons/IconMaterialBolt"
import { IconMaterialBorder } from "../icons/IconMaterialBorder"
import { IconMaterialBorderAll } from "../icons/IconMaterialBorderAll"
import { IconMaterialBorderBottom } from "../icons/IconMaterialBorderBottom"
import { IconMaterialBorderClear } from "../icons/IconMaterialBorderClear"
import { IconMaterialBorderColor } from "../icons/IconMaterialBorderColor"
import { IconMaterialBorderHorizontal } from "../icons/IconMaterialBorderHorizontal"
import { IconMaterialBorderInner } from "../icons/IconMaterialBorderInner"
import { IconMaterialBorderLeft } from "../icons/IconMaterialBorderLeft"
import { IconMaterialBorderOuter } from "../icons/IconMaterialBorderOuter"
import { IconMaterialBorderRight } from "../icons/IconMaterialBorderRight"
import { IconMaterialBorderStyle } from "../icons/IconMaterialBorderStyle"
import { IconMaterialBorderTop } from "../icons/IconMaterialBorderTop"
import { IconMaterialBorderVertical } from "../icons/IconMaterialBorderVertical"
import { IconMaterialBreakfastDining } from "../icons/IconMaterialBreakfastDining"
import { IconMaterialBrowserNotSupported } from "../icons/IconMaterialBrowserNotSupported"
import { IconMaterialBrowserUpdated } from "../icons/IconMaterialBrowserUpdated"
import { IconMaterialBrunchDining } from "../icons/IconMaterialBrunchDining"
import { IconMaterialBubbleChart } from "../icons/IconMaterialBubbleChart"
import { IconMaterialBusAlert } from "../icons/IconMaterialBusAlert"
import { IconMaterialCached } from "../icons/IconMaterialCached"
import { IconMaterialCancel } from "../icons/IconMaterialCancel"
import { IconMaterialCandlestickChart } from "../icons/IconMaterialCandlestickChart"
import { IconMaterialCarCrash } from "../icons/IconMaterialCarCrash"
import { IconMaterialCarRental } from "../icons/IconMaterialCarRental"
import { IconMaterialCarRepair } from "../icons/IconMaterialCarRepair"
import { IconMaterialCast } from "../icons/IconMaterialCast"
import { IconMaterialCastConnected } from "../icons/IconMaterialCastConnected"
import { IconMaterialCastForEducation } from "../icons/IconMaterialCastForEducation"
import { IconMaterialCastle } from "../icons/IconMaterialCastle"
import { IconMaterialCategory } from "../icons/IconMaterialCategory"
import { IconMaterialCelebration } from "../icons/IconMaterialCelebration"
import { IconMaterialChangeCircle } from "../icons/IconMaterialChangeCircle"
import { IconMaterialCheck } from "../icons/IconMaterialCheck"
import { IconMaterialCheckBox } from "../icons/IconMaterialCheckBox"
import { IconMaterialCheckBoxOutlineBlank } from "../icons/IconMaterialCheckBoxOutlineBlank"
import { IconMaterialCheckboxOff } from "../icons/IconMaterialCheckboxOff"
import { IconMaterialCheckboxOn } from "../icons/IconMaterialCheckboxOn"
import { IconMaterialChecklist } from "../icons/IconMaterialChecklist"
import { IconMaterialChecklistRtl } from "../icons/IconMaterialChecklistRtl"
import { IconMaterialChevronDoubleDown } from "../icons/IconMaterialChevronDoubleDown"
import { IconMaterialChevronDoubleLeft } from "../icons/IconMaterialChevronDoubleLeft"
import { IconMaterialChevronDoubleP } from "../icons/IconMaterialChevronDoubleP"
import { IconMaterialChevronDoubleRight } from "../icons/IconMaterialChevronDoubleRight"
import { IconMaterialChevronDown } from "../icons/IconMaterialChevronDown"
import { IconMaterialChevronLeft } from "../icons/IconMaterialChevronLeft"
import { IconMaterialChevronP } from "../icons/IconMaterialChevronP"
import { IconMaterialChevronRight } from "../icons/IconMaterialChevronRight"
import { IconMaterialChurch } from "../icons/IconMaterialChurch"
import { IconMaterialCleaningServices } from "../icons/IconMaterialCleaningServices"
import { IconMaterialClearAll } from "../icons/IconMaterialClearAll"
import { IconMaterialClip } from "../icons/IconMaterialClip"
import { IconMaterialClose } from "../icons/IconMaterialClose"
import { IconMaterialCloseFullscreen } from "../icons/IconMaterialCloseFullscreen"
import { IconMaterialCode } from "../icons/IconMaterialCode"
import { IconMaterialColor } from "../icons/IconMaterialColor"
import { IconMaterialCompareArrows } from "../icons/IconMaterialCompareArrows"
import { IconMaterialCompassCalibration } from "../icons/IconMaterialCompassCalibration"
import { IconMaterialComputed } from "../icons/IconMaterialComputed"
import { IconMaterialComputer } from "../icons/IconMaterialComputer"
import { IconMaterialConnectedTv } from "../icons/IconMaterialConnectedTv"
import { IconMaterialConnectingAirports } from "../icons/IconMaterialConnectingAirports"
import { IconMaterialContent } from "../icons/IconMaterialContent"
import { IconMaterialCorner } from "../icons/IconMaterialCorner"
import { IconMaterialCreateNewFolder } from "../icons/IconMaterialCreateNewFolder"
import { IconMaterialCrisisAlert } from "../icons/IconMaterialCrisisAlert"
import { IconMaterialCursor } from "../icons/IconMaterialCursor"
import { IconMaterialCustom } from "../icons/IconMaterialCustom"
import { IconMaterialDataArray } from "../icons/IconMaterialDataArray"
import { IconMaterialDataObject } from "../icons/IconMaterialDataObject"
import { IconMaterialDataset } from "../icons/IconMaterialDataset"
import { IconMaterialDelete } from "../icons/IconMaterialDelete"
import { IconMaterialDeleteForever } from "../icons/IconMaterialDeleteForever"
import { IconMaterialDeleteSweep } from "../icons/IconMaterialDeleteSweep"
import { IconMaterialDeliveryDining } from "../icons/IconMaterialDeliveryDining"
import { IconMaterialDensityMedium } from "../icons/IconMaterialDensityMedium"
import { IconMaterialDepartureBoard } from "../icons/IconMaterialDepartureBoard"
import { IconMaterialDesignServices } from "../icons/IconMaterialDesignServices"
import { IconMaterialDesktopMac } from "../icons/IconMaterialDesktopMac"
import { IconMaterialDesktopWindows } from "../icons/IconMaterialDesktopWindows"
import { IconMaterialDeveloperBoard } from "../icons/IconMaterialDeveloperBoard"
import { IconMaterialDeveloperBoardOff } from "../icons/IconMaterialDeveloperBoardOff"
import { IconMaterialDeviceCustom } from "../icons/IconMaterialDeviceCustom"
import { IconMaterialDeviceDesktop } from "../icons/IconMaterialDeviceDesktop"
import { IconMaterialDeviceHub } from "../icons/IconMaterialDeviceHub"
import { IconMaterialDeviceLaptop } from "../icons/IconMaterialDeviceLaptop"
import { IconMaterialDeviceMobile } from "../icons/IconMaterialDeviceMobile"
import { IconMaterialDeviceTablet } from "../icons/IconMaterialDeviceTablet"
import { IconMaterialDeviceTv } from "../icons/IconMaterialDeviceTv"
import { IconMaterialDeviceUnknown } from "../icons/IconMaterialDeviceUnknown"
import { IconMaterialDeviceWatch } from "../icons/IconMaterialDeviceWatch"
import { IconMaterialDevicesOther } from "../icons/IconMaterialDevicesOther"
import { IconMaterialDiamond } from "../icons/IconMaterialDiamond"
import { IconMaterialDinnerDining } from "../icons/IconMaterialDinnerDining"
import { IconMaterialDirectionLtr } from "../icons/IconMaterialDirectionLtr"
import { IconMaterialDirectionRtl } from "../icons/IconMaterialDirectionRtl"
import { IconMaterialDirections } from "../icons/IconMaterialDirections"
import { IconMaterialDirectionsBike } from "../icons/IconMaterialDirectionsBike"
import { IconMaterialDirectionsBoat } from "../icons/IconMaterialDirectionsBoat"
import { IconMaterialDirectionsBoatFilled } from "../icons/IconMaterialDirectionsBoatFilled"
import { IconMaterialDirectionsBus } from "../icons/IconMaterialDirectionsBus"
import { IconMaterialDirectionsBusFilled } from "../icons/IconMaterialDirectionsBusFilled"
import { IconMaterialDirectionsCar } from "../icons/IconMaterialDirectionsCar"
import { IconMaterialDirectionsCarFilled } from "../icons/IconMaterialDirectionsCarFilled"
import { IconMaterialDirectionsRailway } from "../icons/IconMaterialDirectionsRailway"
import { IconMaterialDirectionsRailwayFilled } from "../icons/IconMaterialDirectionsRailwayFilled"
import { IconMaterialDirectionsRun } from "../icons/IconMaterialDirectionsRun"
import { IconMaterialDirectionsSubway } from "../icons/IconMaterialDirectionsSubway"
import { IconMaterialDirectionsSubwayFilled } from "../icons/IconMaterialDirectionsSubwayFilled"
import { IconMaterialDirectionsTransit } from "../icons/IconMaterialDirectionsTransit"
import { IconMaterialDirectionsTransitFilled } from "../icons/IconMaterialDirectionsTransitFilled"
import { IconMaterialDirectionsWalk } from "../icons/IconMaterialDirectionsWalk"
import { IconMaterialDisabledByDefault } from "../icons/IconMaterialDisabledByDefault"
import { IconMaterialDisplay } from "../icons/IconMaterialDisplay"
import { IconMaterialDoNotDisturbOn } from "../icons/IconMaterialDoNotDisturbOn"
import { IconMaterialDock } from "../icons/IconMaterialDock"
import { IconMaterialDoneAll } from "../icons/IconMaterialDoneAll"
import { IconMaterialDoneOutline } from "../icons/IconMaterialDoneOutline"
import { IconMaterialDoubleArrow } from "../icons/IconMaterialDoubleArrow"
import { IconMaterialDownload } from "../icons/IconMaterialDownload"
import { IconMaterialDownloadDone } from "../icons/IconMaterialDownloadDone"
import { IconMaterialDownloadForOffline } from "../icons/IconMaterialDownloadForOffline"
import { IconMaterialDownloading } from "../icons/IconMaterialDownloading"
import { IconMaterialDragHandle } from "../icons/IconMaterialDragHandle"
import { IconMaterialDragIndicator } from "../icons/IconMaterialDragIndicator"
import { IconMaterialDraw } from "../icons/IconMaterialDraw"
import { IconMaterialDryCleaning } from "../icons/IconMaterialDryCleaning"
import { IconMaterialEarbuds } from "../icons/IconMaterialEarbuds"
import { IconMaterialEarbudsBattery } from "../icons/IconMaterialEarbudsBattery"
import { IconMaterialEditAttributes } from "../icons/IconMaterialEditAttributes"
import { IconMaterialEditLocation } from "../icons/IconMaterialEditLocation"
import { IconMaterialEditLocationAlt } from "../icons/IconMaterialEditLocationAlt"
import { IconMaterialEditNote } from "../icons/IconMaterialEditNote"
import { IconMaterialEditRoad } from "../icons/IconMaterialEditRoad"
import { IconMaterialEdited } from "../icons/IconMaterialEdited"
import { IconMaterialEgg } from "../icons/IconMaterialEgg"
import { IconMaterialEggAlt } from "../icons/IconMaterialEggAlt"
import { IconMaterialElectricBike } from "../icons/IconMaterialElectricBike"
import { IconMaterialElectricCar } from "../icons/IconMaterialElectricCar"
import { IconMaterialElectricMoped } from "../icons/IconMaterialElectricMoped"
import { IconMaterialElectricRickshaw } from "../icons/IconMaterialElectricRickshaw"
import { IconMaterialElectricScooter } from "../icons/IconMaterialElectricScooter"
import { IconMaterialElectricalServices } from "../icons/IconMaterialElectricalServices"
import { IconMaterialEmergency } from "../icons/IconMaterialEmergency"
import { IconMaterialEmergencyRecording } from "../icons/IconMaterialEmergencyRecording"
import { IconMaterialEmergencyShare } from "../icons/IconMaterialEmergencyShare"
import { IconMaterialEmpty } from "../icons/IconMaterialEmpty"
import { IconMaterialEvStation } from "../icons/IconMaterialEvStation"
import { IconMaterialExitToApp } from "../icons/IconMaterialExitToApp"
import { IconMaterialExpand } from "../icons/IconMaterialExpand"
import { IconMaterialExpandCircleDown } from "../icons/IconMaterialExpandCircleDown"
import { IconMaterialFactory } from "../icons/IconMaterialFactory"
import { IconMaterialFastfood } from "../icons/IconMaterialFastfood"
import { IconMaterialFavorite } from "../icons/IconMaterialFavorite"
import { IconMaterialFestival } from "../icons/IconMaterialFestival"
import { IconMaterialFileOpen } from "../icons/IconMaterialFileOpen"
import { IconMaterialFilterList } from "../icons/IconMaterialFilterList"
import { IconMaterialFireHydrantAlt } from "../icons/IconMaterialFireHydrantAlt"
import { IconMaterialFireTruck } from "../icons/IconMaterialFireTruck"
import { IconMaterialFirstPage } from "../icons/IconMaterialFirstPage"
import { IconMaterialFitHorizontal } from "../icons/IconMaterialFitHorizontal"
import { IconMaterialFitVertical } from "../icons/IconMaterialFitVertical"
import { IconMaterialFlight } from "../icons/IconMaterialFlight"
import { IconMaterialFlightClass } from "../icons/IconMaterialFlightClass"
import { IconMaterialFont } from "../icons/IconMaterialFont"
import { IconMaterialFontFamily } from "../icons/IconMaterialFontFamily"
import { IconMaterialFontLetterSpacing } from "../icons/IconMaterialFontLetterSpacing"
import { IconMaterialFontLineHeight } from "../icons/IconMaterialFontLineHeight"
import { IconMaterialFontSize } from "../icons/IconMaterialFontSize"
import { IconMaterialFontTextAlignCenter } from "../icons/IconMaterialFontTextAlignCenter"
import { IconMaterialFontTextAlignJustify } from "../icons/IconMaterialFontTextAlignJustify"
import { IconMaterialFontTextAlignLeft } from "../icons/IconMaterialFontTextAlignLeft"
import { IconMaterialFontTextAlignRight } from "../icons/IconMaterialFontTextAlignRight"
import { IconMaterialFontTextDecoration } from "../icons/IconMaterialFontTextDecoration"
import { IconMaterialFontTextWrap } from "../icons/IconMaterialFontTextWrap"
import { IconMaterialFontWeight } from "../icons/IconMaterialFontWeight"
import { IconMaterialForest } from "../icons/IconMaterialForest"
import { IconMaterialForkLeft } from "../icons/IconMaterialForkLeft"
import { IconMaterialForkRight } from "../icons/IconMaterialForkRight"
import { IconMaterialFormatAlignCenter } from "../icons/IconMaterialFormatAlignCenter"
import { IconMaterialFormatAlignJustify } from "../icons/IconMaterialFormatAlignJustify"
import { IconMaterialFormatAlignLeft } from "../icons/IconMaterialFormatAlignLeft"
import { IconMaterialFormatAlignRight } from "../icons/IconMaterialFormatAlignRight"
import { IconMaterialFormatBold } from "../icons/IconMaterialFormatBold"
import { IconMaterialFormatClear } from "../icons/IconMaterialFormatClear"
import { IconMaterialFormatColorFill } from "../icons/IconMaterialFormatColorFill"
import { IconMaterialFormatColorReset } from "../icons/IconMaterialFormatColorReset"
import { IconMaterialFormatColorText } from "../icons/IconMaterialFormatColorText"
import { IconMaterialFormatIndentDecrease } from "../icons/IconMaterialFormatIndentDecrease"
import { IconMaterialFormatIndentIncrease } from "../icons/IconMaterialFormatIndentIncrease"
import { IconMaterialFormatItalic } from "../icons/IconMaterialFormatItalic"
import { IconMaterialFormatLineSpacing } from "../icons/IconMaterialFormatLineSpacing"
import { IconMaterialFormatListBulleted } from "../icons/IconMaterialFormatListBulleted"
import { IconMaterialFormatListNumbered } from "../icons/IconMaterialFormatListNumbered"
import { IconMaterialFormatListNumberedRtl } from "../icons/IconMaterialFormatListNumberedRtl"
import { IconMaterialFormatPaint } from "../icons/IconMaterialFormatPaint"
import { IconMaterialFormatQuote } from "../icons/IconMaterialFormatQuote"
import { IconMaterialFormatShapes } from "../icons/IconMaterialFormatShapes"
import { IconMaterialFormatSize } from "../icons/IconMaterialFormatSize"
import { IconMaterialFormatStrikethrough } from "../icons/IconMaterialFormatStrikethrough"
import { IconMaterialFormatTextdirectionLToR } from "../icons/IconMaterialFormatTextdirectionLToR"
import { IconMaterialFormatTextdirectionRToL } from "../icons/IconMaterialFormatTextdirectionRToL"
import { IconMaterialFormatUnderlined } from "../icons/IconMaterialFormatUnderlined"
import { IconMaterialFort } from "../icons/IconMaterialFort"
import { IconMaterialForward } from "../icons/IconMaterialForward"
import { IconMaterialFullscreen } from "../icons/IconMaterialFullscreen"
import { IconMaterialFullscreenExit } from "../icons/IconMaterialFullscreenExit"
import { IconMaterialFunctions } from "../icons/IconMaterialFunctions"
import { IconMaterialGamepad } from "../icons/IconMaterialGamepad"
import { IconMaterialGrade } from "../icons/IconMaterialGrade"
import { IconMaterialHail } from "../icons/IconMaterialHail"
import { IconMaterialHandyman } from "../icons/IconMaterialHandyman"
import { IconMaterialHardware } from "../icons/IconMaterialHardware"
import { IconMaterialHeadphones } from "../icons/IconMaterialHeadphones"
import { IconMaterialHeadphonesBattery } from "../icons/IconMaterialHeadphonesBattery"
import { IconMaterialHeadset } from "../icons/IconMaterialHeadset"
import { IconMaterialHeadsetMic } from "../icons/IconMaterialHeadsetMic"
import { IconMaterialHeadsetOff } from "../icons/IconMaterialHeadsetOff"
import { IconMaterialHeartPlus } from "../icons/IconMaterialHeartPlus"
import { IconMaterialHeight } from "../icons/IconMaterialHeight"
import { IconMaterialHexagon } from "../icons/IconMaterialHexagon"
import { IconMaterialHighlight } from "../icons/IconMaterialHighlight"
import { IconMaterialHome } from "../icons/IconMaterialHome"
import { IconMaterialHomeMax } from "../icons/IconMaterialHomeMax"
import { IconMaterialHomeMini } from "../icons/IconMaterialHomeMini"
import { IconMaterialHomeRepairService } from "../icons/IconMaterialHomeRepairService"
import { IconMaterialHorizontalDistribute } from "../icons/IconMaterialHorizontalDistribute"
import { IconMaterialHorizontalRule } from "../icons/IconMaterialHorizontalRule"
import { IconMaterialHotel } from "../icons/IconMaterialHotel"
import { IconMaterialHvac } from "../icons/IconMaterialHvac"
import { IconMaterialIcecream } from "../icons/IconMaterialIcecream"
import { IconMaterialIconFrame } from "../icons/IconMaterialIconFrame"
import { IconMaterialIconImage } from "../icons/IconMaterialIconImage"
import { IconMaterialIconInput } from "../icons/IconMaterialIconInput"
import { IconMaterialIconText } from "../icons/IconMaterialIconText"
import { IconMaterialImage } from "../icons/IconMaterialImage"
import { IconMaterialIndeterminateCheckBox } from "../icons/IconMaterialIndeterminateCheckBox"
import { IconMaterialInputType } from "../icons/IconMaterialInputType"
import { IconMaterialInsertChart } from "../icons/IconMaterialInsertChart"
import { IconMaterialInsertChartOutlined } from "../icons/IconMaterialInsertChartOutlined"
import { IconMaterialInsertComment } from "../icons/IconMaterialInsertComment"
import { IconMaterialInsertDriveFile } from "../icons/IconMaterialInsertDriveFile"
import { IconMaterialInsertEmoticon } from "../icons/IconMaterialInsertEmoticon"
import { IconMaterialInsertInvitation } from "../icons/IconMaterialInsertInvitation"
import { IconMaterialInsertLink } from "../icons/IconMaterialInsertLink"
import { IconMaterialInsertPageBreak } from "../icons/IconMaterialInsertPageBreak"
import { IconMaterialInsertPhoto } from "../icons/IconMaterialInsertPhoto"
import { IconMaterialIosShare } from "../icons/IconMaterialIosShare"
import { IconMaterialKebabDining } from "../icons/IconMaterialKebabDining"
import { IconMaterialKey } from "../icons/IconMaterialKey"
import { IconMaterialKeyboard } from "../icons/IconMaterialKeyboard"
import { IconMaterialKeyboardAlt } from "../icons/IconMaterialKeyboardAlt"
import { IconMaterialKeyboardArrowDown } from "../icons/IconMaterialKeyboardArrowDown"
import { IconMaterialKeyboardArrowLeft } from "../icons/IconMaterialKeyboardArrowLeft"
import { IconMaterialKeyboardArrowRight } from "../icons/IconMaterialKeyboardArrowRight"
import { IconMaterialKeyboardArrowUp } from "../icons/IconMaterialKeyboardArrowUp"
import { IconMaterialKeyboardBackspace } from "../icons/IconMaterialKeyboardBackspace"
import { IconMaterialKeyboardCapslock } from "../icons/IconMaterialKeyboardCapslock"
import { IconMaterialKeyboardCommandKey } from "../icons/IconMaterialKeyboardCommandKey"
import { IconMaterialKeyboardControlKey } from "../icons/IconMaterialKeyboardControlKey"
import { IconMaterialKeyboardDoubleArrowDown } from "../icons/IconMaterialKeyboardDoubleArrowDown"
import { IconMaterialKeyboardDoubleArrowLeft } from "../icons/IconMaterialKeyboardDoubleArrowLeft"
import { IconMaterialKeyboardDoubleArrowRight } from "../icons/IconMaterialKeyboardDoubleArrowRight"
import { IconMaterialKeyboardDoubleArrowUp } from "../icons/IconMaterialKeyboardDoubleArrowUp"
import { IconMaterialKeyboardHide } from "../icons/IconMaterialKeyboardHide"
import { IconMaterialKeyboardOptionKey } from "../icons/IconMaterialKeyboardOptionKey"
import { IconMaterialKeyboardReturn } from "../icons/IconMaterialKeyboardReturn"
import { IconMaterialKeyboardTab } from "../icons/IconMaterialKeyboardTab"
import { IconMaterialKeyboardVoice } from "../icons/IconMaterialKeyboardVoice"
import { IconMaterialLaptop } from "../icons/IconMaterialLaptop"
import { IconMaterialLaptopChromebook } from "../icons/IconMaterialLaptopChromebook"
import { IconMaterialLaptopMac } from "../icons/IconMaterialLaptopMac"
import { IconMaterialLaptopWindows } from "../icons/IconMaterialLaptopWindows"
import { IconMaterialLastPage } from "../icons/IconMaterialLastPage"
import { IconMaterialLayers } from "../icons/IconMaterialLayers"
import { IconMaterialLayersClear } from "../icons/IconMaterialLayersClear"
import { IconMaterialLibraryAdd } from "../icons/IconMaterialLibraryAdd"
import { IconMaterialLineAxis } from "../icons/IconMaterialLineAxis"
import { IconMaterialLinearScale } from "../icons/IconMaterialLinearScale"
import { IconMaterialLiquor } from "../icons/IconMaterialLiquor"
import { IconMaterialLocalActivity } from "../icons/IconMaterialLocalActivity"
import { IconMaterialLocalAirport } from "../icons/IconMaterialLocalAirport"
import { IconMaterialLocalAtm } from "../icons/IconMaterialLocalAtm"
import { IconMaterialLocalBar } from "../icons/IconMaterialLocalBar"
import { IconMaterialLocalCafe } from "../icons/IconMaterialLocalCafe"
import { IconMaterialLocalCarWash } from "../icons/IconMaterialLocalCarWash"
import { IconMaterialLocalConvenienceStore } from "../icons/IconMaterialLocalConvenienceStore"
import { IconMaterialLocalDining } from "../icons/IconMaterialLocalDining"
import { IconMaterialLocalDrink } from "../icons/IconMaterialLocalDrink"
import { IconMaterialLocalFireDepartment } from "../icons/IconMaterialLocalFireDepartment"
import { IconMaterialLocalFlorist } from "../icons/IconMaterialLocalFlorist"
import { IconMaterialLocalGasStation } from "../icons/IconMaterialLocalGasStation"
import { IconMaterialLocalGroceryStore } from "../icons/IconMaterialLocalGroceryStore"
import { IconMaterialLocalHospital } from "../icons/IconMaterialLocalHospital"
import { IconMaterialLocalHotel } from "../icons/IconMaterialLocalHotel"
import { IconMaterialLocalLaundryService } from "../icons/IconMaterialLocalLaundryService"
import { IconMaterialLocalLibrary } from "../icons/IconMaterialLocalLibrary"
import { IconMaterialLocalMall } from "../icons/IconMaterialLocalMall"
import { IconMaterialLocalMovies } from "../icons/IconMaterialLocalMovies"
import { IconMaterialLocalOffer } from "../icons/IconMaterialLocalOffer"
import { IconMaterialLocalParking } from "../icons/IconMaterialLocalParking"
import { IconMaterialLocalPharmacy } from "../icons/IconMaterialLocalPharmacy"
import { IconMaterialLocalPhone } from "../icons/IconMaterialLocalPhone"
import { IconMaterialLocalPizza } from "../icons/IconMaterialLocalPizza"
import { IconMaterialLocalPlay } from "../icons/IconMaterialLocalPlay"
import { IconMaterialLocalPolice } from "../icons/IconMaterialLocalPolice"
import { IconMaterialLocalPostOffice } from "../icons/IconMaterialLocalPostOffice"
import { IconMaterialLocalPrintshop } from "../icons/IconMaterialLocalPrintshop"
import { IconMaterialLocalSee } from "../icons/IconMaterialLocalSee"
import { IconMaterialLocalShipping } from "../icons/IconMaterialLocalShipping"
import { IconMaterialLocalTaxi } from "../icons/IconMaterialLocalTaxi"
import { IconMaterialLogin } from "../icons/IconMaterialLogin"
import { IconMaterialLogout } from "../icons/IconMaterialLogout"
import { IconMaterialLunchDining } from "../icons/IconMaterialLunchDining"
import { IconMaterialManageSearch } from "../icons/IconMaterialManageSearch"
import { IconMaterialMap } from "../icons/IconMaterialMap"
import { IconMaterialMapsUgc } from "../icons/IconMaterialMapsUgc"
import { IconMaterialMargin } from "../icons/IconMaterialMargin"
import { IconMaterialMedicalInformation } from "../icons/IconMaterialMedicalInformation"
import { IconMaterialMedicalServices } from "../icons/IconMaterialMedicalServices"
import { IconMaterialMemory } from "../icons/IconMaterialMemory"
import { IconMaterialMenu } from "../icons/IconMaterialMenu"
import { IconMaterialMenuBook } from "../icons/IconMaterialMenuBook"
import { IconMaterialMenuOpen } from "../icons/IconMaterialMenuOpen"
import { IconMaterialMerge } from "../icons/IconMaterialMerge"
import { IconMaterialMergeType } from "../icons/IconMaterialMergeType"
import { IconMaterialMinorCrash } from "../icons/IconMaterialMinorCrash"
import { IconMaterialMinus } from "../icons/IconMaterialMinus"
import { IconMaterialMiscellaneousServices } from "../icons/IconMaterialMiscellaneousServices"
import { IconMaterialMode } from "../icons/IconMaterialMode"
import { IconMaterialModeComment } from "../icons/IconMaterialModeComment"
import { IconMaterialModeEdit } from "../icons/IconMaterialModeEdit"
import { IconMaterialModeEditOutline } from "../icons/IconMaterialModeEditOutline"
import { IconMaterialModeOfTravel } from "../icons/IconMaterialModeOfTravel"
import { IconMaterialMonetizationOn } from "../icons/IconMaterialMonetizationOn"
import { IconMaterialMoney } from "../icons/IconMaterialMoney"
import { IconMaterialMoneyOff } from "../icons/IconMaterialMoneyOff"
import { IconMaterialMoneyOffCsred } from "../icons/IconMaterialMoneyOffCsred"
import { IconMaterialMonitor } from "../icons/IconMaterialMonitor"
import { IconMaterialMoped } from "../icons/IconMaterialMoped"
import { IconMaterialMore } from "../icons/IconMaterialMore"
import { IconMaterialMoreHoriz } from "../icons/IconMaterialMoreHoriz"
import { IconMaterialMoreVert } from "../icons/IconMaterialMoreVert"
import { IconMaterialMosque } from "../icons/IconMaterialMosque"
import { IconMaterialMouse } from "../icons/IconMaterialMouse"
import { IconMaterialMoveDown } from "../icons/IconMaterialMoveDown"
import { IconMaterialMoveUp } from "../icons/IconMaterialMoveUp"
import { IconMaterialMoving } from "../icons/IconMaterialMoving"
import { IconMaterialMultilineChart } from "../icons/IconMaterialMultilineChart"
import { IconMaterialMultipleStop } from "../icons/IconMaterialMultipleStop"
import { IconMaterialMuseum } from "../icons/IconMaterialMuseum"
import { IconMaterialMyLocation } from "../icons/IconMaterialMyLocation"
import { IconMaterialNavigation } from "../icons/IconMaterialNavigation"
import { IconMaterialNearMe } from "../icons/IconMaterialNearMe"
import { IconMaterialNearMeDisabled } from "../icons/IconMaterialNearMeDisabled"
import { IconMaterialNightlife } from "../icons/IconMaterialNightlife"
import { IconMaterialNoCrash } from "../icons/IconMaterialNoCrash"
import { IconMaterialNoMeals } from "../icons/IconMaterialNoMeals"
import { IconMaterialNoTransfer } from "../icons/IconMaterialNoTransfer"
import { IconMaterialNone } from "../icons/IconMaterialNone"
import { IconMaterialNotListedLocation } from "../icons/IconMaterialNotListedLocation"
import { IconMaterialNotes } from "../icons/IconMaterialNotes"
import { IconMaterialNumbers } from "../icons/IconMaterialNumbers"
import { IconMaterialOpacity } from "../icons/IconMaterialOpacity"
import { IconMaterialOpenInFull } from "../icons/IconMaterialOpenInFull"
import { IconMaterialOpenInNew } from "../icons/IconMaterialOpenInNew"
import { IconMaterialOpenWith } from "../icons/IconMaterialOpenWith"
import { IconMaterialOrientationHorizontal } from "../icons/IconMaterialOrientationHorizontal"
import { IconMaterialOrientationVertical } from "../icons/IconMaterialOrientationVertical"
import { IconMaterialPadding } from "../icons/IconMaterialPadding"
import { IconMaterialPark } from "../icons/IconMaterialPark"
import { IconMaterialPedalBike } from "../icons/IconMaterialPedalBike"
import { IconMaterialPentagon } from "../icons/IconMaterialPentagon"
import { IconMaterialPerson } from "../icons/IconMaterialPerson"
import { IconMaterialPersonPin } from "../icons/IconMaterialPersonPin"
import { IconMaterialPersonPinCircle } from "../icons/IconMaterialPersonPinCircle"
import { IconMaterialPestControl } from "../icons/IconMaterialPestControl"
import { IconMaterialPestControlRodent } from "../icons/IconMaterialPestControlRodent"
import { IconMaterialPhoneAndroid } from "../icons/IconMaterialPhoneAndroid"
import { IconMaterialPhoneIphone } from "../icons/IconMaterialPhoneIphone"
import { IconMaterialPhonelink } from "../icons/IconMaterialPhonelink"
import { IconMaterialPhonelinkOff } from "../icons/IconMaterialPhonelinkOff"
import { IconMaterialPieChart } from "../icons/IconMaterialPieChart"
import { IconMaterialPieChartOutline } from "../icons/IconMaterialPieChartOutline"
import { IconMaterialPinDrop } from "../icons/IconMaterialPinDrop"
import { IconMaterialPlace } from "../icons/IconMaterialPlace"
import { IconMaterialPlumbing } from "../icons/IconMaterialPlumbing"
import { IconMaterialPlus } from "../icons/IconMaterialPlus"
import { IconMaterialPointOfSale } from "../icons/IconMaterialPointOfSale"
import { IconMaterialPolyline } from "../icons/IconMaterialPolyline"
import { IconMaterialPostAdd } from "../icons/IconMaterialPostAdd"
import { IconMaterialPowerInput } from "../icons/IconMaterialPowerInput"
import { IconMaterialPreview } from "../icons/IconMaterialPreview"
import { IconMaterialPublish } from "../icons/IconMaterialPublish"
import { IconMaterialQueryStats } from "../icons/IconMaterialQueryStats"
import { IconMaterialQuestionMark } from "../icons/IconMaterialQuestionMark"
import { IconMaterialRadioButtonChecked } from "../icons/IconMaterialRadioButtonChecked"
import { IconMaterialRadioButtonUnchecked } from "../icons/IconMaterialRadioButtonUnchecked"
import { IconMaterialRadioOff } from "../icons/IconMaterialRadioOff"
import { IconMaterialRadioOn } from "../icons/IconMaterialRadioOn"
import { IconMaterialRailwayAlert } from "../icons/IconMaterialRailwayAlert"
import { IconMaterialRamenDining } from "../icons/IconMaterialRamenDining"
import { IconMaterialRampLeft } from "../icons/IconMaterialRampLeft"
import { IconMaterialRampRight } from "../icons/IconMaterialRampRight"
import { IconMaterialRateReview } from "../icons/IconMaterialRateReview"
import { IconMaterialRectangle } from "../icons/IconMaterialRectangle"
import { IconMaterialRedo } from "../icons/IconMaterialRedo"
import { IconMaterialRefresh } from "../icons/IconMaterialRefresh"
import { IconMaterialRemove } from "../icons/IconMaterialRemove"
import { IconMaterialRemoveRoad } from "../icons/IconMaterialRemoveRoad"
import { IconMaterialReply } from "../icons/IconMaterialReply"
import { IconMaterialRestaurant } from "../icons/IconMaterialRestaurant"
import { IconMaterialRestaurantMenu } from "../icons/IconMaterialRestaurantMenu"
import { IconMaterialRetry } from "../icons/IconMaterialRetry"
import { IconMaterialRobot } from "../icons/IconMaterialRobot"
import { IconMaterialRoundaboutLeft } from "../icons/IconMaterialRoundaboutLeft"
import { IconMaterialRoundaboutRight } from "../icons/IconMaterialRoundaboutRight"
import { IconMaterialRoute } from "../icons/IconMaterialRoute"
import { IconMaterialRouter } from "../icons/IconMaterialRouter"
import { IconMaterialRunCircle } from "../icons/IconMaterialRunCircle"
import { IconMaterialSafetyCheck } from "../icons/IconMaterialSafetyCheck"
import { IconMaterialSailing } from "../icons/IconMaterialSailing"
import { IconMaterialSatellite } from "../icons/IconMaterialSatellite"
import { IconMaterialScanner } from "../icons/IconMaterialScanner"
import { IconMaterialScatterPlot } from "../icons/IconMaterialScatterPlot"
import { IconMaterialSchema } from "../icons/IconMaterialSchema"
import { IconMaterialScore } from "../icons/IconMaterialScore"
import { IconMaterialScreenRotationAlt } from "../icons/IconMaterialScreenRotationAlt"
import { IconMaterialSearch } from "../icons/IconMaterialSearch"
import { IconMaterialSecurity } from "../icons/IconMaterialSecurity"
import { IconMaterialSend } from "../icons/IconMaterialSend"
import { IconMaterialSetMeal } from "../icons/IconMaterialSetMeal"
import { IconMaterialSettings } from "../icons/IconMaterialSettings"
import { IconMaterialSettingsApplications } from "../icons/IconMaterialSettingsApplications"
import { IconMaterialSettingsBackupRestore } from "../icons/IconMaterialSettingsBackupRestore"
import { IconMaterialShadow } from "../icons/IconMaterialShadow"
import { IconMaterialShapeLine } from "../icons/IconMaterialShapeLine"
import { IconMaterialShare } from "../icons/IconMaterialShare"
import { IconMaterialShoppingCartCheckout } from "../icons/IconMaterialShoppingCartCheckout"
import { IconMaterialShortText } from "../icons/IconMaterialShortText"
import { IconMaterialShowChart } from "../icons/IconMaterialShowChart"
import { IconMaterialSignalCellularAlt } from "../icons/IconMaterialSignalCellularAlt"
import { IconMaterialSignpost } from "../icons/IconMaterialSignpost"
import { IconMaterialSimCard } from "../icons/IconMaterialSimCard"
import { IconMaterialSize } from "../icons/IconMaterialSize"
import { IconMaterialSmartDisplay } from "../icons/IconMaterialSmartDisplay"
import { IconMaterialSmartScreen } from "../icons/IconMaterialSmartScreen"
import { IconMaterialSmartToy } from "../icons/IconMaterialSmartToy"
import { IconMaterialSmartphone } from "../icons/IconMaterialSmartphone"
import { IconMaterialSnowmobile } from "../icons/IconMaterialSnowmobile"
import { IconMaterialSort } from "../icons/IconMaterialSort"
import { IconMaterialSortByAlpha } from "../icons/IconMaterialSortByAlpha"
import { IconMaterialSos } from "../icons/IconMaterialSos"
import { IconMaterialSoupKitchen } from "../icons/IconMaterialSoupKitchen"
import { IconMaterialSpaceBar } from "../icons/IconMaterialSpaceBar"
import { IconMaterialSpeaker } from "../icons/IconMaterialSpeaker"
import { IconMaterialSpeakerGroup } from "../icons/IconMaterialSpeakerGroup"
import { IconMaterialSpread } from "../icons/IconMaterialSpread"
import { IconMaterialSquare } from "../icons/IconMaterialSquare"
import { IconMaterialStackedLineChart } from "../icons/IconMaterialStackedLineChart"
import { IconMaterialStadium } from "../icons/IconMaterialStadium"
import { IconMaterialStar } from "../icons/IconMaterialStar"
import { IconMaterialStarBorder } from "../icons/IconMaterialStarBorder"
import { IconMaterialStarBorderPurple500 } from "../icons/IconMaterialStarBorderPurple500"
import { IconMaterialStarHalf } from "../icons/IconMaterialStarHalf"
import { IconMaterialStarOutline } from "../icons/IconMaterialStarOutline"
import { IconMaterialStarPurple500 } from "../icons/IconMaterialStarPurple500"
import { IconMaterialStart } from "../icons/IconMaterialStart"
import { IconMaterialStoreMallDirectory } from "../icons/IconMaterialStoreMallDirectory"
import { IconMaterialStraight } from "../icons/IconMaterialStraight"
import { IconMaterialStreetview } from "../icons/IconMaterialStreetview"
import { IconMaterialStrikethroughS } from "../icons/IconMaterialStrikethroughS"
import { IconMaterialSubdirectoryArrowRight } from "../icons/IconMaterialSubdirectoryArrowRight"
import { IconMaterialSubscript } from "../icons/IconMaterialSubscript"
import { IconMaterialSubway } from "../icons/IconMaterialSubway"
import { IconMaterialSuperscript } from "../icons/IconMaterialSuperscript"
import { IconMaterialSwapHoriz } from "../icons/IconMaterialSwapHoriz"
import { IconMaterialSwapVert } from "../icons/IconMaterialSwapVert"
import { IconMaterialSwitchAccessShortcut } from "../icons/IconMaterialSwitchAccessShortcut"
import { IconMaterialSynagogue } from "../icons/IconMaterialSynagogue"
import { IconMaterialSync } from "../icons/IconMaterialSync"
import { IconMaterialSyncAlt } from "../icons/IconMaterialSyncAlt"
import { IconMaterialTableChart } from "../icons/IconMaterialTableChart"
import { IconMaterialTableRows } from "../icons/IconMaterialTableRows"
import { IconMaterialTablet } from "../icons/IconMaterialTablet"
import { IconMaterialTabletAndroid } from "../icons/IconMaterialTabletAndroid"
import { IconMaterialTabletMac } from "../icons/IconMaterialTabletMac"
import { IconMaterialTakeoutDining } from "../icons/IconMaterialTakeoutDining"
import { IconMaterialTaxiAlert } from "../icons/IconMaterialTaxiAlert"
import { IconMaterialTempleBuddhist } from "../icons/IconMaterialTempleBuddhist"
import { IconMaterialTempleHindu } from "../icons/IconMaterialTempleHindu"
import { IconMaterialTerminal } from "../icons/IconMaterialTerminal"
import { IconMaterialTerrain } from "../icons/IconMaterialTerrain"
import { IconMaterialTextDecrease } from "../icons/IconMaterialTextDecrease"
import { IconMaterialTextFields } from "../icons/IconMaterialTextFields"
import { IconMaterialTextIncrease } from "../icons/IconMaterialTextIncrease"
import { IconMaterialTheaterComedy } from "../icons/IconMaterialTheaterComedy"
import { IconMaterialThumbDown } from "../icons/IconMaterialThumbDown"
import { IconMaterialThumbP } from "../icons/IconMaterialThumbP"
import { IconMaterialTicket } from "../icons/IconMaterialTicket"
import { IconMaterialTireRepair } from "../icons/IconMaterialTireRepair"
import { IconMaterialTitle } from "../icons/IconMaterialTitle"
import { IconMaterialToggleOff } from "../icons/IconMaterialToggleOff"
import { IconMaterialToggleOn } from "../icons/IconMaterialToggleOn"
import { IconMaterialToken } from "../icons/IconMaterialToken"
import { IconMaterialToys } from "../icons/IconMaterialToys"
import { IconMaterialTraffic } from "../icons/IconMaterialTraffic"
import { IconMaterialTrain } from "../icons/IconMaterialTrain"
import { IconMaterialTram } from "../icons/IconMaterialTram"
import { IconMaterialTransferWithinAStation } from "../icons/IconMaterialTransferWithinAStation"
import { IconMaterialTransitEnterexit } from "../icons/IconMaterialTransitEnterexit"
import { IconMaterialTripOrigin } from "../icons/IconMaterialTripOrigin"
import { IconMaterialTurnLeft } from "../icons/IconMaterialTurnLeft"
import { IconMaterialTurnRight } from "../icons/IconMaterialTurnRight"
import { IconMaterialTurnSharpLeft } from "../icons/IconMaterialTurnSharpLeft"
import { IconMaterialTurnSharpRight } from "../icons/IconMaterialTurnSharpRight"
import { IconMaterialTurnSlightLeft } from "../icons/IconMaterialTurnSlightLeft"
import { IconMaterialTurnSlightRight } from "../icons/IconMaterialTurnSlightRight"
import { IconMaterialTv } from "../icons/IconMaterialTv"
import { IconMaterialTwoWheeler } from "../icons/IconMaterialTwoWheeler"
import { IconMaterialTypeSpecimen } from "../icons/IconMaterialTypeSpecimen"
import { IconMaterialUTurnLeft } from "../icons/IconMaterialUTurnLeft"
import { IconMaterialUTurnRight } from "../icons/IconMaterialUTurnRight"
import { IconMaterialUndo } from "../icons/IconMaterialUndo"
import { IconMaterialUnfoldLess } from "../icons/IconMaterialUnfoldLess"
import { IconMaterialUnfoldMore } from "../icons/IconMaterialUnfoldMore"
import { IconMaterialUpload } from "../icons/IconMaterialUpload"
import { IconMaterialVector } from "../icons/IconMaterialVector"
import { IconMaterialVerticalAlignBottom } from "../icons/IconMaterialVerticalAlignBottom"
import { IconMaterialVerticalAlignCenter } from "../icons/IconMaterialVerticalAlignCenter"
import { IconMaterialVerticalAlignTop } from "../icons/IconMaterialVerticalAlignTop"
import { IconMaterialVerticalDistribute } from "../icons/IconMaterialVerticalDistribute"
import { IconMaterialVideogameAsset } from "../icons/IconMaterialVideogameAsset"
import { IconMaterialVideogameAssetOff } from "../icons/IconMaterialVideogameAssetOff"
import { IconMaterialViewTimeline } from "../icons/IconMaterialViewTimeline"
import { IconMaterialVisibilityOff } from "../icons/IconMaterialVisibilityOff"
import { IconMaterialVolunteerActivism } from "../icons/IconMaterialVolunteerActivism"
import { IconMaterialWarehouse } from "../icons/IconMaterialWarehouse"
import { IconMaterialWatch } from "../icons/IconMaterialWatch"
import { IconMaterialWatchOff } from "../icons/IconMaterialWatchOff"
import { IconMaterialWifi } from "../icons/IconMaterialWifi"
import { IconMaterialWineBar } from "../icons/IconMaterialWineBar"
import { IconMaterialWrapText } from "../icons/IconMaterialWrapText"
import { IconMaterialWrongLocation } from "../icons/IconMaterialWrongLocation"
import { IconMaterialX } from "../icons/IconMaterialX"
import { IconMaterialZoomIn } from "../icons/IconMaterialZoomIn"
import { IconMaterialZoomInMap } from "../icons/IconMaterialZoomInMap"
import { IconMaterialZoomOut } from "../icons/IconMaterialZoomOut"
import { IconMaterialZoomOutMap } from "../icons/IconMaterialZoomOutMap"
import { IconMaterial_360 } from "../icons/IconMaterial_360"
import { IconMissing } from "../icons/IconMissing"
import { IconSeldonAi } from "../icons/IconSeldonAi"
import { IconSeldonAlignBottom } from "../icons/IconSeldonAlignBottom"
import { IconSeldonAlignLeft } from "../icons/IconSeldonAlignLeft"
import { IconSeldonAlignRight } from "../icons/IconSeldonAlignRight"
import { IconSeldonAlignTop } from "../icons/IconSeldonAlignTop"
import { IconSeldonAngle } from "../icons/IconSeldonAngle"
import { IconSeldonBackground } from "../icons/IconSeldonBackground"
import { IconSeldonCodeCube } from "../icons/IconSeldonCodeCube"
import { IconSeldonComponent } from "../icons/IconSeldonComponent"
import { IconSeldonComponentDefault } from "../icons/IconSeldonComponentDefault"
import { IconSeldonComponentVariant } from "../icons/IconSeldonComponentVariant"
import { IconSeldonFrame } from "../icons/IconSeldonFrame"
import { IconSeldonFrameBackground } from "../icons/IconSeldonFrameBackground"
import { IconSeldonFrameColumns } from "../icons/IconSeldonFrameColumns"
import { IconSeldonFrameRows } from "../icons/IconSeldonFrameRows"
import { IconSeldonGap } from "../icons/IconSeldonGap"
import { IconSeldonGradient } from "../icons/IconSeldonGradient"
import { IconSeldonHexagon } from "../icons/IconSeldonHexagon"
import { IconSeldonHidden } from "../icons/IconSeldonHidden"
import { IconSeldonIcon } from "../icons/IconSeldonIcon"
import { IconSeldonImage } from "../icons/IconSeldonImage"
import { IconSeldonImageFit } from "../icons/IconSeldonImageFit"
import { IconSeldonInput } from "../icons/IconSeldonInput"
import { IconSeldonLines } from "../icons/IconSeldonLines"
import { IconSeldonPositionBottom } from "../icons/IconSeldonPositionBottom"
import { IconSeldonPositionBottomLeft } from "../icons/IconSeldonPositionBottomLeft"
import { IconSeldonPositionBottomRight } from "../icons/IconSeldonPositionBottomRight"
import { IconSeldonPositionCenter } from "../icons/IconSeldonPositionCenter"
import { IconSeldonPositionLeft } from "../icons/IconSeldonPositionLeft"
import { IconSeldonPositionRight } from "../icons/IconSeldonPositionRight"
import { IconSeldonPositionTop } from "../icons/IconSeldonPositionTop"
import { IconSeldonPositionTopLeft } from "../icons/IconSeldonPositionTopLeft"
import { IconSeldonPositionTopRight } from "../icons/IconSeldonPositionTopRight"
import { IconSeldonReset } from "../icons/IconSeldonReset"
import { IconSeldonScreen } from "../icons/IconSeldonScreen"
import { IconSeldonSketchCircle } from "../icons/IconSeldonSketchCircle"
import { IconSeldonSketchPencil } from "../icons/IconSeldonSketchPencil"
import { IconSeldonSketchRectangle } from "../icons/IconSeldonSketchRectangle"
import { IconSeldonSketchText } from "../icons/IconSeldonSketchText"
import { IconSeldonStep } from "../icons/IconSeldonStep"
import { IconSeldonStub } from "../icons/IconSeldonStub"
import { IconSeldonSwatch } from "../icons/IconSeldonSwatch"
import { IconSeldonText } from "../icons/IconSeldonText"
import { IconSeldonTheme } from "../icons/IconSeldonTheme"
import { IconSeldonToolArrow } from "../icons/IconSeldonToolArrow"
import { IconSeldonToolComponent } from "../icons/IconSeldonToolComponent"
import { IconSeldonToolImageAi } from "../icons/IconSeldonToolImageAi"
import { IconSeldonToolSketch } from "../icons/IconSeldonToolSketch"
import { IconSeldonValuePx } from "../icons/IconSeldonValuePx"
import { IconSeldonValueRem } from "../icons/IconSeldonValueRem"
import { IconSocialDiscord } from "../icons/IconSocialDiscord"
import { IconSocialFacebook } from "../icons/IconSocialFacebook"
import { IconSocialFlickr } from "../icons/IconSocialFlickr"
import { IconSocialGithub } from "../icons/IconSocialGithub"
import { IconSocialInstagram } from "../icons/IconSocialInstagram"
import { IconSocialLinkedin } from "../icons/IconSocialLinkedin"
import { IconSocialMedium } from "../icons/IconSocialMedium"
import { IconSocialPinterest } from "../icons/IconSocialPinterest"
import { IconSocialQuora } from "../icons/IconSocialQuora"
import { IconSocialReddit } from "../icons/IconSocialReddit"
import { IconSocialSnapchat } from "../icons/IconSocialSnapchat"
import { IconSocialSpotify } from "../icons/IconSocialSpotify"
import { IconSocialTelegram } from "../icons/IconSocialTelegram"
import { IconSocialTiktok } from "../icons/IconSocialTiktok"
import { IconSocialTumblr } from "../icons/IconSocialTumblr"
import { IconSocialTwitch } from "../icons/IconSocialTwitch"
import { IconSocialTwitter } from "../icons/IconSocialTwitter"
import { IconSocialVimeo } from "../icons/IconSocialVimeo"
import { IconSocialWhatsapp } from "../icons/IconSocialWhatsapp"
import { IconSocialYoutube } from "../icons/IconSocialYoutube"

export interface IconProps extends SVGAttributes<SVGElement> {
  className?: string
  icon?:
    | "__default__"
    | "material-360"
    | "material-accountCircle"
    | "material-add"
    | "material-addBox"
    | "material-addBusiness"
    | "material-addChart"
    | "material-addCircle"
    | "material-addComment"
    | "material-addLocation"
    | "material-addLocationAlt"
    | "material-addRoad"
    | "material-adfScanner"
    | "material-agriculture"
    | "material-airlineStops"
    | "material-airlines"
    | "material-alignHorizontalCenter"
    | "material-alignHorizontalLeft"
    | "material-alignHorizontalRight"
    | "material-alignVerticalBottom"
    | "material-alignVerticalCenter"
    | "material-alignVerticalTop"
    | "material-altRoute"
    | "material-apps"
    | "material-areaChart"
    | "material-arrowBack"
    | "material-arrowBackIosNew"
    | "material-arrowCircleDown"
    | "material-arrowCircleLeft"
    | "material-arrowCircleRight"
    | "material-arrowCircleUp"
    | "material-arrowDownward"
    | "material-arrowDropDown"
    | "material-arrowDropDownCircle"
    | "material-arrowDropUp"
    | "material-arrowForward"
    | "material-arrowForwardIos"
    | "material-arrowLeft"
    | "material-arrowOutward"
    | "material-arrowRight"
    | "material-arrowRightAlt"
    | "material-arrowUpward"
    | "material-assistantNavigation"
    | "material-atm"
    | "material-attachFile"
    | "material-attachMoney"
    | "material-attractions"
    | "material-autoGraph"
    | "material-autorenew"
    | "material-backspace"
    | "material-badge"
    | "material-bakeryDining"
    | "material-barChart"
    | "material-battery0Bar"
    | "material-batteryFullAlt"
    | "material-batteryHoriz000"
    | "material-batteryHoriz050"
    | "material-batteryHoriz075"
    | "material-batteryLow"
    | "material-beenhere"
    | "material-bikeScooter"
    | "material-block"
    | "material-bolt"
    | "material-border"
    | "material-borderAll"
    | "material-borderBottom"
    | "material-borderClear"
    | "material-borderColor"
    | "material-borderHorizontal"
    | "material-borderInner"
    | "material-borderLeft"
    | "material-borderOuter"
    | "material-borderRight"
    | "material-borderStyle"
    | "material-borderTop"
    | "material-borderVertical"
    | "material-breakfastDining"
    | "material-browserNotSupported"
    | "material-browserUpdated"
    | "material-brunchDining"
    | "material-bubbleChart"
    | "material-busAlert"
    | "material-cached"
    | "material-cancel"
    | "material-candlestickChart"
    | "material-carCrash"
    | "material-carRental"
    | "material-carRepair"
    | "material-cast"
    | "material-castConnected"
    | "material-castForEducation"
    | "material-castle"
    | "material-category"
    | "material-celebration"
    | "material-changeCircle"
    | "material-check"
    | "material-checkBox"
    | "material-checkBoxOutlineBlank"
    | "material-checkboxOff"
    | "material-checkboxOn"
    | "material-checklist"
    | "material-checklistRtl"
    | "material-chevronDoubleDown"
    | "material-chevronDoubleLeft"
    | "material-chevronDoubleP"
    | "material-chevronDoubleRight"
    | "material-chevronDown"
    | "material-chevronLeft"
    | "material-chevronP"
    | "material-chevronRight"
    | "material-church"
    | "material-cleaningServices"
    | "material-clearAll"
    | "material-clip"
    | "material-close"
    | "material-closeFullscreen"
    | "material-code"
    | "material-color"
    | "material-compareArrows"
    | "material-compassCalibration"
    | "material-computed"
    | "material-computer"
    | "material-connectedTv"
    | "material-connectingAirports"
    | "material-content"
    | "material-corner"
    | "material-createNewFolder"
    | "material-crisisAlert"
    | "material-cursor"
    | "material-custom"
    | "material-dataArray"
    | "material-dataObject"
    | "material-dataset"
    | "material-delete"
    | "material-deleteForever"
    | "material-deleteSweep"
    | "material-deliveryDining"
    | "material-densityMedium"
    | "material-departureBoard"
    | "material-designServices"
    | "material-desktopMac"
    | "material-desktopWindows"
    | "material-developerBoard"
    | "material-developerBoardOff"
    | "material-deviceCustom"
    | "material-deviceDesktop"
    | "material-deviceHub"
    | "material-deviceLaptop"
    | "material-deviceMobile"
    | "material-deviceTV"
    | "material-deviceTablet"
    | "material-deviceUnknown"
    | "material-deviceWatch"
    | "material-devicesOther"
    | "material-diamond"
    | "material-dinnerDining"
    | "material-directionLTR"
    | "material-directionRTL"
    | "material-directions"
    | "material-directionsBike"
    | "material-directionsBoat"
    | "material-directionsBoatFilled"
    | "material-directionsBus"
    | "material-directionsBusFilled"
    | "material-directionsCar"
    | "material-directionsCarFilled"
    | "material-directionsRailway"
    | "material-directionsRailwayFilled"
    | "material-directionsRun"
    | "material-directionsSubway"
    | "material-directionsSubwayFilled"
    | "material-directionsTransit"
    | "material-directionsTransitFilled"
    | "material-directionsWalk"
    | "material-disabledByDefault"
    | "material-display"
    | "material-doNotDisturbOn"
    | "material-dock"
    | "material-doneAll"
    | "material-doneOutline"
    | "material-doubleArrow"
    | "material-download"
    | "material-downloadDone"
    | "material-downloadForOffline"
    | "material-downloading"
    | "material-dragHandle"
    | "material-dragIndicator"
    | "material-draw"
    | "material-dryCleaning"
    | "material-earbuds"
    | "material-earbudsBattery"
    | "material-editAttributes"
    | "material-editLocation"
    | "material-editLocationAlt"
    | "material-editNote"
    | "material-editRoad"
    | "material-edited"
    | "material-egg"
    | "material-eggAlt"
    | "material-electricBike"
    | "material-electricCar"
    | "material-electricMoped"
    | "material-electricRickshaw"
    | "material-electricScooter"
    | "material-electricalServices"
    | "material-emergency"
    | "material-emergencyRecording"
    | "material-emergencyShare"
    | "material-empty"
    | "material-evStation"
    | "material-exitToApp"
    | "material-expand"
    | "material-expandCircleDown"
    | "material-factory"
    | "material-fastfood"
    | "material-favorite"
    | "material-festival"
    | "material-fileOpen"
    | "material-filterList"
    | "material-fireHydrantAlt"
    | "material-fireTruck"
    | "material-firstPage"
    | "material-fitHorizontal"
    | "material-fitVertical"
    | "material-flight"
    | "material-flightClass"
    | "material-font"
    | "material-fontFamily"
    | "material-fontLetterSpacing"
    | "material-fontLineHeight"
    | "material-fontSize"
    | "material-fontTextAlignCenter"
    | "material-fontTextAlignJustify"
    | "material-fontTextAlignLeft"
    | "material-fontTextAlignRight"
    | "material-fontTextDecoration"
    | "material-fontTextWrap"
    | "material-fontWeight"
    | "material-forest"
    | "material-forkLeft"
    | "material-forkRight"
    | "material-formatAlignCenter"
    | "material-formatAlignJustify"
    | "material-formatAlignLeft"
    | "material-formatAlignRight"
    | "material-formatBold"
    | "material-formatClear"
    | "material-formatColorFill"
    | "material-formatColorReset"
    | "material-formatColorText"
    | "material-formatIndentDecrease"
    | "material-formatIndentIncrease"
    | "material-formatItalic"
    | "material-formatLineSpacing"
    | "material-formatListBulleted"
    | "material-formatListNumbered"
    | "material-formatListNumberedRtl"
    | "material-formatPaint"
    | "material-formatQuote"
    | "material-formatShapes"
    | "material-formatSize"
    | "material-formatStrikethrough"
    | "material-formatTextdirectionLToR"
    | "material-formatTextdirectionRToL"
    | "material-formatUnderlined"
    | "material-fort"
    | "material-forward"
    | "material-fullscreen"
    | "material-fullscreenExit"
    | "material-functions"
    | "material-gamepad"
    | "material-grade"
    | "material-hail"
    | "material-handyman"
    | "material-hardware"
    | "material-headphones"
    | "material-headphonesBattery"
    | "material-headset"
    | "material-headsetMic"
    | "material-headsetOff"
    | "material-heartPlus"
    | "material-height"
    | "material-hexagon"
    | "material-highlight"
    | "material-home"
    | "material-homeMax"
    | "material-homeMini"
    | "material-homeRepairService"
    | "material-horizontalDistribute"
    | "material-horizontalRule"
    | "material-hotel"
    | "material-hvac"
    | "material-icecream"
    | "material-iconFrame"
    | "material-iconImage"
    | "material-iconInput"
    | "material-iconText"
    | "material-image"
    | "material-indeterminateCheckBox"
    | "material-inputType"
    | "material-insertChart"
    | "material-insertChartOutlined"
    | "material-insertComment"
    | "material-insertDriveFile"
    | "material-insertEmoticon"
    | "material-insertInvitation"
    | "material-insertLink"
    | "material-insertPageBreak"
    | "material-insertPhoto"
    | "material-iosShare"
    | "material-kebabDining"
    | "material-key"
    | "material-keyboard"
    | "material-keyboardAlt"
    | "material-keyboardArrowDown"
    | "material-keyboardArrowLeft"
    | "material-keyboardArrowRight"
    | "material-keyboardArrowUp"
    | "material-keyboardBackspace"
    | "material-keyboardCapslock"
    | "material-keyboardCommandKey"
    | "material-keyboardControlKey"
    | "material-keyboardDoubleArrowDown"
    | "material-keyboardDoubleArrowLeft"
    | "material-keyboardDoubleArrowRight"
    | "material-keyboardDoubleArrowUp"
    | "material-keyboardHide"
    | "material-keyboardOptionKey"
    | "material-keyboardReturn"
    | "material-keyboardTab"
    | "material-keyboardVoice"
    | "material-laptop"
    | "material-laptopChromebook"
    | "material-laptopMac"
    | "material-laptopWindows"
    | "material-lastPage"
    | "material-layers"
    | "material-layersClear"
    | "material-libraryAdd"
    | "material-lineAxis"
    | "material-linearScale"
    | "material-liquor"
    | "material-localActivity"
    | "material-localAirport"
    | "material-localAtm"
    | "material-localBar"
    | "material-localCafe"
    | "material-localCarWash"
    | "material-localConvenienceStore"
    | "material-localDining"
    | "material-localDrink"
    | "material-localFireDepartment"
    | "material-localFlorist"
    | "material-localGasStation"
    | "material-localGroceryStore"
    | "material-localHospital"
    | "material-localHotel"
    | "material-localLaundryService"
    | "material-localLibrary"
    | "material-localMall"
    | "material-localMovies"
    | "material-localOffer"
    | "material-localParking"
    | "material-localPharmacy"
    | "material-localPhone"
    | "material-localPizza"
    | "material-localPlay"
    | "material-localPolice"
    | "material-localPostOffice"
    | "material-localPrintshop"
    | "material-localSee"
    | "material-localShipping"
    | "material-localTaxi"
    | "material-login"
    | "material-logout"
    | "material-lunchDining"
    | "material-manageSearch"
    | "material-map"
    | "material-mapsUgc"
    | "material-margin"
    | "material-medicalInformation"
    | "material-medicalServices"
    | "material-memory"
    | "material-menu"
    | "material-menuBook"
    | "material-menuOpen"
    | "material-merge"
    | "material-mergeType"
    | "material-minorCrash"
    | "material-minus"
    | "material-miscellaneousServices"
    | "material-mode"
    | "material-modeComment"
    | "material-modeEdit"
    | "material-modeEditOutline"
    | "material-modeOfTravel"
    | "material-monetizationOn"
    | "material-money"
    | "material-moneyOff"
    | "material-moneyOffCsred"
    | "material-monitor"
    | "material-moped"
    | "material-more"
    | "material-moreHoriz"
    | "material-moreVert"
    | "material-mosque"
    | "material-mouse"
    | "material-moveDown"
    | "material-moveUp"
    | "material-moving"
    | "material-multilineChart"
    | "material-multipleStop"
    | "material-museum"
    | "material-myLocation"
    | "material-navigation"
    | "material-nearMe"
    | "material-nearMeDisabled"
    | "material-nightlife"
    | "material-noCrash"
    | "material-noMeals"
    | "material-noTransfer"
    | "material-none"
    | "material-notListedLocation"
    | "material-notes"
    | "material-numbers"
    | "material-opacity"
    | "material-openInFull"
    | "material-openInNew"
    | "material-openWith"
    | "material-orientationHorizontal"
    | "material-orientationVertical"
    | "material-padding"
    | "material-park"
    | "material-pedalBike"
    | "material-pentagon"
    | "material-person"
    | "material-personPin"
    | "material-personPinCircle"
    | "material-pestControl"
    | "material-pestControlRodent"
    | "material-phoneAndroid"
    | "material-phoneIphone"
    | "material-phonelink"
    | "material-phonelinkOff"
    | "material-pieChart"
    | "material-pieChartOutline"
    | "material-pinDrop"
    | "material-place"
    | "material-plumbing"
    | "material-plus"
    | "material-pointOfSale"
    | "material-polyline"
    | "material-postAdd"
    | "material-powerInput"
    | "material-preview"
    | "material-publish"
    | "material-queryStats"
    | "material-questionMark"
    | "material-radioButtonChecked"
    | "material-radioButtonUnchecked"
    | "material-radioOff"
    | "material-radioOn"
    | "material-railwayAlert"
    | "material-ramenDining"
    | "material-rampLeft"
    | "material-rampRight"
    | "material-rateReview"
    | "material-rectangle"
    | "material-redo"
    | "material-refresh"
    | "material-remove"
    | "material-removeRoad"
    | "material-reply"
    | "material-restaurant"
    | "material-restaurantMenu"
    | "material-retry"
    | "material-robot"
    | "material-roundaboutLeft"
    | "material-roundaboutRight"
    | "material-route"
    | "material-router"
    | "material-runCircle"
    | "material-safetyCheck"
    | "material-sailing"
    | "material-satellite"
    | "material-scanner"
    | "material-scatterPlot"
    | "material-schema"
    | "material-score"
    | "material-screenRotationAlt"
    | "material-search"
    | "material-security"
    | "material-send"
    | "material-setMeal"
    | "material-settings"
    | "material-settingsApplications"
    | "material-settingsBackupRestore"
    | "material-shadow"
    | "material-shapeLine"
    | "material-share"
    | "material-shoppingCartCheckout"
    | "material-shortText"
    | "material-showChart"
    | "material-signalCellularAlt"
    | "material-signpost"
    | "material-simCard"
    | "material-size"
    | "material-smartDisplay"
    | "material-smartScreen"
    | "material-smartToy"
    | "material-smartphone"
    | "material-snowmobile"
    | "material-sort"
    | "material-sortByAlpha"
    | "material-sos"
    | "material-soupKitchen"
    | "material-spaceBar"
    | "material-speaker"
    | "material-speakerGroup"
    | "material-spread"
    | "material-square"
    | "material-stackedLineChart"
    | "material-stadium"
    | "material-star"
    | "material-starBorder"
    | "material-starBorderPurple500"
    | "material-starHalf"
    | "material-starOutline"
    | "material-starPurple500"
    | "material-start"
    | "material-storeMallDirectory"
    | "material-straight"
    | "material-streetview"
    | "material-strikethroughS"
    | "material-subdirectoryArrowRight"
    | "material-subscript"
    | "material-subway"
    | "material-superscript"
    | "material-swapHoriz"
    | "material-swapVert"
    | "material-switchAccessShortcut"
    | "material-synagogue"
    | "material-sync"
    | "material-syncAlt"
    | "material-tableChart"
    | "material-tableRows"
    | "material-tablet"
    | "material-tabletAndroid"
    | "material-tabletMac"
    | "material-takeoutDining"
    | "material-taxiAlert"
    | "material-templeBuddhist"
    | "material-templeHindu"
    | "material-terminal"
    | "material-terrain"
    | "material-textDecrease"
    | "material-textFields"
    | "material-textIncrease"
    | "material-theaterComedy"
    | "material-thumbDown"
    | "material-thumbP"
    | "material-ticket"
    | "material-tireRepair"
    | "material-title"
    | "material-toggleOff"
    | "material-toggleOn"
    | "material-token"
    | "material-toys"
    | "material-traffic"
    | "material-train"
    | "material-tram"
    | "material-transferWithinAStation"
    | "material-transitEnterexit"
    | "material-tripOrigin"
    | "material-turnLeft"
    | "material-turnRight"
    | "material-turnSharpLeft"
    | "material-turnSharpRight"
    | "material-turnSlightLeft"
    | "material-turnSlightRight"
    | "material-tv"
    | "material-twoWheeler"
    | "material-typeSpecimen"
    | "material-uTurnLeft"
    | "material-uTurnRight"
    | "material-undo"
    | "material-unfoldLess"
    | "material-unfoldMore"
    | "material-upload"
    | "material-vector"
    | "material-verticalAlignBottom"
    | "material-verticalAlignCenter"
    | "material-verticalAlignTop"
    | "material-verticalDistribute"
    | "material-videogameAsset"
    | "material-videogameAssetOff"
    | "material-viewTimeline"
    | "material-visibilityOff"
    | "material-volunteerActivism"
    | "material-warehouse"
    | "material-watch"
    | "material-watchOff"
    | "material-wifi"
    | "material-wineBar"
    | "material-wrapText"
    | "material-wrongLocation"
    | "material-x"
    | "material-zoomIn"
    | "material-zoomInMap"
    | "material-zoomOut"
    | "material-zoomOutMap"
    | "missing"
    | "seldon-ai"
    | "seldon-alignBottom"
    | "seldon-alignLeft"
    | "seldon-alignRight"
    | "seldon-alignTop"
    | "seldon-angle"
    | "seldon-background"
    | "seldon-codeCube"
    | "seldon-component"
    | "seldon-componentDefault"
    | "seldon-componentVariant"
    | "seldon-frame"
    | "seldon-frameBackground"
    | "seldon-frameColumns"
    | "seldon-frameRows"
    | "seldon-gap"
    | "seldon-gradient"
    | "seldon-hexagon"
    | "seldon-hidden"
    | "seldon-icon"
    | "seldon-image"
    | "seldon-imageFit"
    | "seldon-input"
    | "seldon-lines"
    | "seldon-positionBottom"
    | "seldon-positionBottomLeft"
    | "seldon-positionBottomRight"
    | "seldon-positionCenter"
    | "seldon-positionLeft"
    | "seldon-positionRight"
    | "seldon-positionTop"
    | "seldon-positionTopLeft"
    | "seldon-positionTopRight"
    | "seldon-reset"
    | "seldon-screen"
    | "seldon-sketchCircle"
    | "seldon-sketchPencil"
    | "seldon-sketchRectangle"
    | "seldon-sketchText"
    | "seldon-step"
    | "seldon-stub"
    | "seldon-swatch"
    | "seldon-text"
    | "seldon-theme"
    | "seldon-toolArrow"
    | "seldon-toolComponent"
    | "seldon-toolImageAi"
    | "seldon-toolSketch"
    | "seldon-valuePx"
    | "seldon-valueRem"
    | "social-facebook"
    | "social-youtube"
    | "social-whatsapp"
    | "social-instagram"
    | "social-tiktok"
    | "social-twitter"
    | "social-linkedin"
    | "social-snapchat"
    | "social-pinterest"
    | "social-reddit"
    | "social-telegram"
    | "social-discord"
    | "social-twitch"
    | "social-github"
    | "social-spotify"
    | "social-tumblr"
    | "social-vimeo"
    | "social-flickr"
    | "social-medium"
    | "social-quora"
}

/**
 * Icon
 *
 * Level: Primitive
 *
 * Intent: Displays a vector or symbolic icon representing an action or concept.
 *
 * Tags: icon, symbol, graphic, primitive, UI, decoration
 *
 * @example
 * ```tsx
 * <Icon
 *   icon="__default__"
 * />
 * ```
 */
export function Icon({
  className = "",
  icon = "__default__",
  ...props
}: IconProps) {
  let Icon = iconMap[icon || "__default__"]
  if (!Icon) {
    Icon = iconMap["__default__"]
    console.error(`Icon ${icon} not found. Falling back to the default icon.`)
  }
  return <Icon className={"sdn-icon " + className} {...props} />
}
const iconMap = {
  __default__: IconDefault,
  "material-send": IconMaterialSend,
  "social-twitter": IconSocialTwitter,
  "social-linkedin": IconSocialLinkedin,
  "social-instagram": IconSocialInstagram,
  "material-add": IconMaterialAdd,
  "material-remove": IconMaterialRemove,
}
